queue_rules:
  - name: default
    conditions:
      - status-success=Travis CI - Pull Request
      - label!=do-not-merge

pull_request_rules:
  - name: queue when bot user
    conditions:
      - author=alfresco-build
      - status-success=Travis CI - Pull Request
      - label!=do-not-merge
    actions:
      queue:
        method: squash
        name: default
  - name: queue when all (and at least one) requested reviews approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - status-success=Travis CI - Pull Request
      - status-success=license/cla
      - label!=do-not-merge
    actions:
      queue:
        method: squash
        name: default
