import:
  - source: Alfresco/alfresco-build-tools:.travis.helm_install.yml@v1.1.0
  - source: Alfresco/alfresco-build-tools:.travis.rancher_cli_kubernetes_config.yml@v1.1.0
  - source: Alfresco/alfresco-build-tools:.travis.rancher_cli_install.yml@v1.1.0
  - source: Alfresco/alfresco-build-tools:.travis.yq_install.yml@v1.1.0
  - source: Alfresco/alfresco-build-tools:.travis.helm-docs_install.yml@v1.1.0
  - source: Alfresco/alfresco-build-tools:.travis.checkov_install.yml@v1.1.0
  - source: Alfresco/alfresco-build-tools:.travis.kubepug_install.yml@v1.1.0
  - source: Alfresco/alfresco-build-tools:.travis.pre-commit.yml@v1.1.0
  - source: Alfresco/alfresco-build-tools:.travis.common.yml@v1.1.0

branches:
  only:
    - master

before_install:
  - |
    git config user.name "Alfresco Build User"
    git config user.email "build_user@alfresco.com"
    echo TRAVIS_PULL_REQUEST_BRANCH=$(TRAVIS_PULL_REQUEST_BRANCH)
    echo TRAVIS_BRANCH=$(TRAVIS_BRANCH)
    JX_RELEASE_VERSION=1.0.43
    curl -Ls https://github.com/jenkins-x-plugins/jx-release-version/releases/download/v${JX_RELEASE_VERSION}/jx-release-version-$(uname | tr '[:upper:]' '[:lower:]')-amd64.tar.gz | tar xz -C $HOME/bin/ jx-release-version

    echo $(jx-release-version) > VERSION
    export VERSION=$(cat VERSION)
    export PREVIEW_NAME=$(echo "$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER" | tr '[:upper:]' '[:lower:]' | tr . -)

jobs:
  include:

    - name: Verify build
      stage: test
      script: |
        cd charts/activiti-cloud-full-example
        make build

    - name: Create tag package helm chart and release it
      stage: publish
      script: |
        cd charts/activiti-cloud-full-example
        make version
        make tag
        make release
        make github
