{{- if  (index  .Values  "alfresco-identity-service" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
  labels:
    app: {{ template "activiti-cloud-identity.name" . }}
    chart: {{ template "activiti-cloud-identity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  "alfresco-aps-realm.json": {{ tpl (.Files.Get "alfresco-aps-realm.json") . | b64enc | quote }}
{{- end}}
