apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/Alfresco/alfresco-process-releases
      reusePullRequest: true
      changes:
        - command:
            name: sh
            args:
              - -c
              - |
                mvn -ntp versions:set-property -Dproperty=activiti-cloud-full-chart.version -DnewVersion=${VERSION}
                mvn -ntp versions:set-property -Dproperty=activiti-cloud-application.version -DnewVersion=${ACTIVITI_CLOUD_APPLICATION_VERSION}
