runtime-bundle:
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
activiti-cloud-query:
  liquibase:
    enabled: false
  args:
    - -jar
    - rest.jar
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
activiti-cloud-consumer:
  enabled: true
