{{- if not .Values.global.keycloak.useExistingClientSecret -}}
{{- $clientSecretName := tpl .Values.global.keycloak.clientSecretName $ | required "global.keycloak.clientSecretName is required" }}
{{- $clientId := tpl .Values.global.keycloak.clientId $ | required "global.keycloak.clientId is required" }}
{{- $clientSecret := tpl .Values.global.keycloak.clientSecret $ | required "global.keycloak.clientSecret is required" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $clientSecretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    application: {{ tpl .Values.global.application.name $ }}
type: Opaque
data:
  clientId: {{ $clientId | b64enc }}
  clientSecret: {{ $clientSecret | b64enc }}
{{- end }}
