{{- if not .Values.global.keycloak.useExistingClientSecret -}}
{{- $clientSecretName := tpl .Values.global.keycloak.clientSecretName $ | required "global.keycloak.clientSecretName is required" }}
{{- $clientSecret := tpl .Values.global.keycloak.clientSecret $ }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $clientSecretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    application: {{ tpl .Values.global.application.name $ }}
type: Opaque
data:
  clientId: {{ tpl .Values.global.keycloak.clientId $ | required "global.keycloak.clientId is required" | b64enc }}
  {{- if $clientSecret }}
  clientSecret: {{ $clientSecret | b64enc }}
  {{- else }}
  clientSecret: {{ include "getOrGenerateRandomSecret" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $clientSecretName "Key" "clientSecret" "Length" 32) }}
  {{- end }}
{{- end }}
