{{- if index .Values "runtime-bundle" "autoscaling" "enabled" -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: runtime-bundle
spec:
  maxReplicas: {{ index .Values "runtime-bundle" "autoscaling" "maxReplicas" }}
  minReplicas: {{ index .Values "runtime-bundle" "autoscaling" "minReplicas" }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: runtime-bundle
  targetCPUUtilizationPercentage: {{ index .Values "runtime-bundle" "autoscaling" "targetCPUUtilizationPercentage" }}
{{- end }}
