{{- if index .Values "activiti-cloud-identity" "enabled" -}}
apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
type: Opaque
data:
  {{- $defaultRealm := fromJson (.Files.Get "realm.json") }}
  {{- $realmName := include "common.keycloak-realm" . }}
{{/*  {{- $clientName := include "common.keycloak-resource" . }}*/}}
{{/*  {{- $client := merge (dict "clientId" $clientName) (index .Values "activiti-cloud-identity" "realm" "alfresco" "client") }}*/}}
{{/*  {{- $clients := list $client }}*/}}
{{/*  {{- $roles := index .Values "activiti-cloud-identity" "realm" "alfresco" "extraRealmRoles" }}*/}}
{{/*  {{- $users := index .Values "activiti-cloud-identity" "realm" "alfresco" "extraUsers" }}*/}}
{{/*  {{- $groups := index .Values "activiti-cloud-identity" "realm" "alfresco" "extraGroups" }}*/}}
{{/*  {{- $realm := merge $defaultRealm (dict "realm" $realmName "clients" $clients "roles" $roles "users" $users) }}*/}}
  {{- $realm := merge $defaultRealm (dict "realm" $realmName) }}
  realm.json: {{ mustToPrettyJson $realm | b64enc }}
{{- end }}
