{{- if index .Values "activiti-cloud-identity" "enabled" -}}
apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
type: Opaque
data:
  {{- $realmName := include "common.keycloak-realm" . }}
  {{- $clientName := include "common.keycloak-resource" . }}
  {{- $client := merge (dict "clientId" $clientName) (index .Values "activiti-cloud-identity" "realm" "alfresco" "client") }}
  {{- $clients := list $client }}
  {{- $roles := index .Values "activiti-cloud-identity" "realm" "alfresco" "extraRealmRoles" }}
  {{- $users := index .Values "activiti-cloud-identity" "realm" "alfresco" "extraUsers" }}
  {{- $groups := index .Values "activiti-cloud-identity" "realm" "alfresco" "extraGroups" }}
  {{- $realm := dict "realm" $realmName "clients" $clients "roles" $roles "users" $users }}
  realm.json: {{ toPrettyJson $realm | b64enc }}
{{- end }}
