{{- if index .Values "activiti-cloud-identity" "enabled" -}}
apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    application: activiti
type: Opaque
data:
  {{- $defaultRealm := fromJson (.Files.Get "realm.json") -}}
  {{- $realmName := include "common.keycloak-realm" . }}
  {{- $resourceName := include "common.keycloak-resource" . }}

  {{- $users := index $defaultRealm "users" | default list -}}
  {{- $extraUsers := index .Values "activiti-cloud-identity" "realm" "extraUsers" | default list }}
  {{- $users = concat $users $extraUsers -}}

  {{- $groups := index $defaultRealm "groups" | default list -}}
  {{- $extraGroups := index .Values "activiti-cloud-identity" "realm" "extraGroups" | default list }}
  {{- $groups = concat $groups $extraGroups -}}

  {{- $clients := index $defaultRealm "clients" | default list -}}
  {{- $extraClients := index .Values "activiti-cloud-identity" "realm" "extraClients" | default list }}
  {{- $clients = concat $clients $extraClients -}}
  {{- range $val := $clients -}}
    {{- if eq (index . "clientId") "activiti" }}
      {{- $_ := set . "clientId" $resourceName -}}
    {{- end -}}
  {{- end -}}

  {{- $realmRoles := index $defaultRealm "roles" "realm" | default list -}}
  {{- $extraRealmRoles := index .Values "activiti-cloud-identity" "realm" "extraRealmRoles" | default list }}
  {{- $realmRoles = concat $realmRoles $extraRealmRoles -}}

  {{- $clientRoles := index $defaultRealm "roles" "client" | default list -}}
  {{- $extraClientRoles := index .Values "activiti-cloud-identity" "realm" "extraClientRoles" | default dict }}
  {{- $clientRoles = mergeOverwrite $clientRoles $extraClientRoles -}}

  {{- $activitiClientRoles := index $clientRoles "activiti" | default list -}}
  {{- $clientRoles = set $clientRoles $resourceName $activitiClientRoles -}}
  {{- $clientRoles = unset $clientRoles "activiti" -}}

  {{- $roles := dict "realm" $realmRoles "client" $clientRoles -}}

  {{- $realm := mergeOverwrite $defaultRealm (dict "realm" $realmName "clients" $clients "roles" $roles "groups" $groups "users" $users) }}
  realm.json: {{ mustToPrettyJson $realm | b64enc }}
{{- end }}
