name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - milestoned
  workflow_dispatch:

env:
  CHART_DIR: "charts/activiti-cloud-full-example"

jobs:

  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check dependabot/fork build
        if: github.secret_source == 'Dependabot' || (github.secret_source == 'None' && github.event.action != 'milestoned')
        uses: Alfresco/alfresco-build-tools/.github/actions/github-require-secrets@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
        with:
          dependabot-error-message: "This PR requires additional validation, please set the milestone to 'Validating' or ask a reviewer to approve it."
          none-error-message: "This PR requires additional validation, please set the milestone to 'Validating'."
      - name: Setup Helm Docs
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
        with:
          version: 1.13.1
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@e1bb78184f5dd3690fb1089d6c4f51295f9dff48 # v12.1839.0
        with:
          framework: kubernetes
      - name: pre-commit
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
        with:
          skip_checkout: true
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@ca46236c6ce584ae24bc6283ba8dcf4b3ec8a066 # v5.0.4

  build:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-build-chart@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/resolve-preview-name@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
        id: resolve-preview

      - name: Setup Cluster
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-kind@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0

      - name: Compute Keycloak Client Secret
        id: compute-keycloak-secret
        shell: bash
        run: echo "result=$(uuidgen)" >> $GITHUB_OUTPUT

      - name: Execute helm upgrade dry-run
        env:
          CHART_DIR: ${{ env.CHART_DIR }}
          NAMESPACE: ${{ steps.resolve-preview.outputs.preview-name }}
          DOMAIN: "example"
          KEYCLOAK_SECRET: ${{ steps.compute-keycloak-secret.outputs.result }}
        shell: bash
        run: |
          NAMESPACE_LOWERCASE=$(echo ${NAMESPACE} | tr "[:upper:]" "[:lower:]")
          helm upgrade $NAMESPACE_LOWERCASE $CHART_DIR \
            --install \
            --set global.gateway.domain=$DOMAIN \
            --set global.keycloak.clientSecret=$KEYCLOAK_SECRET \
            --namespace $NAMESPACE_LOWERCASE \
            --wait \
            --dry-run

  parse-next-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    outputs:
      next-release: ${{ steps.parse-next-release.outputs.next-release }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Parse next release
        id: parse-next-release
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-parse-next-release@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
        with:
          chart-dir: ${{ env.CHART_DIR }}

  publish:
    needs: parse-next-release
    if: github.event_name == 'push'
    uses: Alfresco/alfresco-build-tools/.github/workflows/helm-publish-new-package-version.yml@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
    with:
      next-version: ${{ needs.parse-next-release.outputs.next-release }}
      chart-dir: charts/activiti-cloud-full-example
      helm-charts-repo: Activiti/activiti-cloud-helm-charts
      helm-charts-repo-branch: gh-pages
    secrets: inherit

  promote:
    if: github.event_name == 'push'
    needs:
      - publish
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.publish.outputs.version }}
      DEVELOPMENT_BRANCH: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: echo ACTIVITI_CLOUD_APPLICATION_VERSION=`yq .runtime-bundle.image.tag charts/activiti-cloud-full-example/values.yaml` >> $GITHUB_ENV
      - uses: Alfresco/alfresco-build-tools/.github/actions/jx-updatebot-pr@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          version: ${{ env.VERSION }}
          auto-merge: 'true'
          labels: 'be-propagation,${{ env.DEVELOPMENT_BRANCH }}'
          base-branch-name: ${{ env.DEVELOPMENT_BRANCH }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          git-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-author-name: ${{ secrets.BOT_GITHUB_USERNAME }}

  notify:
    runs-on: ubuntu-latest
    needs:
      - build
      - publish
      - promote
    if: always() && failure() && github.event_name == 'push'
    steps:
      - name: Teams Notification
        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@10cea6c0b390c4f8af21d9dc1670d581bd10319f # v18.13.0
        with:
          webhook-url: ${{ secrets.TEAMS_NOTIFICATION_WORKFLOW_WEBHOOK }}
