name: Create Pre-release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

env:
  CHART_NAME: activiti-cloud-full-example
  CHART_DIR: "charts/activiti-cloud-full-example"
  HELM_REPO_BASE_URL: https://activiti.github.io/activiti-cloud-helm-charts
  HELM_REPO: Activiti/activiti-cloud-helm-charts
  HELM_REPO_NAME: activiti-cloud-helm-charts
  HELM_REPO_BRANCH: gh-pages
  HELM_REPO_SUBFOLDER: .

jobs:
  prerelease:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - id: helm-package-chart
        name: Package Helm chart
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-package-chart@21fb2cdff9e78dae9d11604252d778c2f1af8a43 # v7.1.1
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - id: helm-publish-chart
        name: Publish Helm chart
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-publish-chart@21fb2cdff9e78dae9d11604252d778c2f1af8a43 # v7.1.1
        with:
          chart-package: ${{ steps.helm-package-chart.outputs.package-file-path }}
          helm-charts-repo: ${{ env.HELM_REPO }}
          helm-charts-repo-branch: ${{ env.HELM_REPO_BRANCH }}
          helm-charts-repo-subfolder: ${{ env.HELM_REPO_SUBFOLDER }}
          helm-charts-repo-base-url: ${{ env.HELM_REPO_BASE_URL }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}

      - uses: Activiti/activiti-scripts/.github/actions/wait-for-chart@acb1b5e1b5eb550892b9df30843dec9294833dd0 # 8.6.0
        with:
          chart-name: ${{ env.CHART_NAME }}
          version: ${{ env.VERSION }}
          helm-repo-name:  ${{ env.HELM_REPO_NAME }}
          helm-repo-url: ${{ env.HELM_REPO_BASE_URL }}

  notify:
    runs-on: ubuntu-latest
    needs:
      - prerelease
    if: always() && failure() && github.event_name == 'push'
    steps:
      - name: Slack Notification
        uses: Alfresco/alfresco-build-tools/.github/actions/send-slack-notification@21fb2cdff9e78dae9d11604252d778c2f1af8a43 # v7.1.1
        with:
          channel-id: 'C04CARMB605' # eng-hxp-studio-releases-gh-notifs, to be renamed eng-automate-releases-gh-notifs
          token: ${{ secrets.SLACK_NOTIFICATION_BOT_TOKEN }}
