name: Create Pre-release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

env:
  CHART_NAME: activiti-cloud-full-example
  CHART_DIR: "charts/activiti-cloud-full-example"
  HELM_REPO_BASE_URL: https://activiti.github.io/activiti-cloud-helm-charts
  HELM_REPO: Activiti/activiti-cloud-helm-charts
  HELM_REPO_NAME: activiti-cloud-helm-charts
  HELM_REPO_BRANCH: gh-pages
  HELM_REPO_SUBFOLDER: .

jobs:
  prerelease:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - id: helm-package-chart
        name: Package Helm chart
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-package-chart@e87345fb177248fc5bdc7838107f098438818df1 # v18.21.0
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - id: helm-publish-chart
        name: Publish Helm chart
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-publish-chart@e87345fb177248fc5bdc7838107f098438818df1 # v18.21.0
        with:
          chart-package: ${{ steps.helm-package-chart.outputs.package-file-path }}
          helm-charts-repo: ${{ env.HELM_REPO }}
          helm-charts-repo-branch: ${{ env.HELM_REPO_BRANCH }}
          helm-charts-repo-subfolder: ${{ env.HELM_REPO_SUBFOLDER }}
          helm-charts-repo-base-url: ${{ env.HELM_REPO_BASE_URL }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}

      - uses: Activiti/activiti-scripts/.github/actions/wait-for-chart@dabe8f78a1f944f77a2e1fe0c001ae404a88d0f0 # 9.0.0
        with:
          chart-name: ${{ env.CHART_NAME }}
          version: ${{ env.VERSION }}
          helm-repo-name:  ${{ env.HELM_REPO_NAME }}
          helm-repo-url: ${{ env.HELM_REPO_BASE_URL }}

  notify:
    runs-on: ubuntu-latest
    needs:
      - prerelease
    if: always() && failure() && github.event_name == 'push'
    steps:
      - name: Teams Notification
        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@e87345fb177248fc5bdc7838107f098438818df1 # v18.21.0
        with:
          webhook-url: ${{ secrets.TEAMS_NOTIFICATION_WORKFLOW_WEBHOOK }}
