name: Versions propagation auto-merge
on:
  pull_request:
    types: [labeled]
    branches:
      - develop

jobs:
  versions-propagation-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/automate-propagation@bbb4eed7a36d87eddec4a607553f519b0323dfb0 # v12.4.1
      with:
        auto-merge-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        approval-token: ${{ secrets.GITHUB_TOKEN }}
