name: Versions propagation auto-merge
on:
  pull_request:
    types: [labeled]
    branches:
      - develop

jobs:
  versions-propagation-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/automate-propagation@d2333816055ff07f7497ff8f8176f789dbe7e811 # v12.7.0
      with:
        auto-merge-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        approval-token: ${{ secrets.GITHUB_TOKEN }}
